version: '3.8'

services:
  evoweb:
    build: .
    ports:
      - "3330:3330"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
    restart: always
