services:
  evoweb:
    container_name: evoweb
    build:
      context: .
      dockerfile: Dockerfile
    image: evoweb:latest
    extra_hosts:
      - "bridgeserver:host-gateway"
    ports:
      - "3330:3330"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3330
    volumes:
      - ./.env:/app/.env
      - ./data:/app/data
      - ./logs:/app/logs
      - ./.session.json:/app/.session.json
    restart: unless-stopped
